spring:
  appication:
    name: mint-task
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:mindb}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  flyway:
    baselineOnMigrate: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    root: INFO

api:
  currency-exchange:
    list-url: https://currency-exchange.p.rapidapi.com/listquotes
    exchange-url: https://currency-exchange.p.rapidapi.com/exchange
    key: 431b1812demshfa66e987efe1fcfp17e0c7jsnef9d7f82d8fc
    host: currency-exchange.p.rapidapi.com
